// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmLhKHNvHZwFqx8VFKLrQcTEXoynWKQ44',
    appId: '1:292564712989:web:81d8b4121d7fd43167d0f4',
    messagingSenderId: '292564712989',
    projectId: 'fir-crud-8e95b',
    authDomain: 'fir-crud-8e95b.firebaseapp.com',
    storageBucket: 'fir-crud-8e95b.appspot.com',
    measurementId: 'G-6XPFD7ESQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZU2RoV4gdF3M4qgvH_rVJ0557QLXuX28',
    appId: '1:292564712989:android:0f876c3eeca251d967d0f4',
    messagingSenderId: '292564712989',
    projectId: 'fir-crud-8e95b',
    storageBucket: 'fir-crud-8e95b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeNsDYB0Zed24Zklae1Oj4z-tmjKg2fis',
    appId: '1:292564712989:ios:2e3cfa79750e80c467d0f4',
    messagingSenderId: '292564712989',
    projectId: 'fir-crud-8e95b',
    storageBucket: 'fir-crud-8e95b.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
